### ISSUE TITLE
Installation instructions as per README do not work

### ISSUE THREAD

**Issue by insectopalo** [ZWang-Lab/LSKAT#1]
Following the steps in the README file do not result in the installation of the package.
R CMD INSTALL LSKAT
Warning: invalid package ‘LSKAT’
Error: ERROR: no packages specified

**Comment by wzhy2000** [comment]
I am sorry about that.  There is a wrong command line in README.MD. After you download source code, you don't need to enter the LSKAT folder,  just run R to install the package as follows:

git clone https://github.com/ZWang-Lab/LSKAT.git
R CMD INSTALL LSKAT
